# Data Containers

couchdbData:
  image: busybox
  volumes:
    - /usr/local/lib/npmo/couchdb:/usr/local/var/lib/couchdb

elasticsearchData:
  image: busybox
  volumes:
    - /usr/local/lib/npmo/elasticsearch:/data

postgresData:
  image: busybox
  volumes:
    - /usr/local/lib/npmo/postgresql:/var/lib/postgresql/data

authData:
  image: busybox
  volumes:
    - /usr/local/lib/npmo/data:/etc/npme/data

packagesData:
  image: busybox
  volumes:
    - /usr/local/lib/npmo/packages:/etc/npme/packages

# couchdb

couchdbprimary:
  build: roles/couchdb
  volumes_from:
    - "couchdbData"
  ports:
    - "55984:5984"

# registry

auth:
  expose:
    - "5000"
  environment:
    - AUTHENTICATION_METHOD=fake
    - AUTHORIZATION_METHOD=fake
    - GITHUB_HOST=
    - GITHUB_ORG=
    - LOGIN_CACHE_REDIS=redis://redis:6379
    - REJECT_UNAUTHORIZED=0
    - SESSION_HANDLER=redis
    - SESSION_HANDLER=redis
    - SHARED_FETCH_SECRET=abc123
  image: bcoe/npm-auth-ws:1.0.6
  links:
    - redis
  restart: always
  volumes_from:
    - "authData"
  env_file: .env

frontdoor:
  build: roles/registry
  environment:
    - AUTH_FETCH=false
    - AUTH_HOST=http://auth:5000
    - AUTHENTICATION_METHOD=fake
    - AUTHORIZATION_METHOD=fake
    - BINARIES_HOST=http://nginx:8000
    - BINARY_DIRECTORY=/etc/npme/packages
    - COUCH_URL=http://admin:admin@couchdbprimary:5984/registry
    - COUCH_URL_REMOTE=https://skimdb.npmjs.com/registry
    - GITHUB_HOST=
    - LOGIN_CACHE_REDIS=redis://redis:6379
    - PROXY_URL=
    - READ_THROUGH_CACHE=false
    - REJECT_UNAUTHORIZED=0
    - SESSION_HANDLER=redis
    - SHARED_FETCH_SECRET=abc123
    - VALIDATE_HOST=http://validate:5001
  links:
    - auth
    - couchdbprimary
    - redis
    - validate
    - nginx
  ports:
    - "8080:8080"
  restart: always
  volumes_from:
    - "authData"
    - "packagesData"

nginx:
  image: bcoe/nginx:1.0.0
  expose:
    - "8000"
  restart: always
  volumes_from:
    - "packagesData"

redis:
  expose:
    - "6379"
  image: redis
  restart: always

validate:
  environment:
    - BINARY_DIRECTORY=/etc/npme/packages
    - COUCH_URL=http://admin:admin@couchdbprimary:5984/registry
    - REJECT_UNAUTHORIZED=0
  expose:
    - "5001"
  image: bcoe/validate-and-store:1.0.0
  links:
    - couchdbprimary
  restart: always
  volumes_from:
    - "packagesData"
  env_file: .env

# website

postgres:
  expose:
    - "5432"
  image: bcoe/postgres:9.3
  restart: always
  volumes_from:
    - "postgresData"

rrfollower:
  build: roles/rr-follower
  restart: always
  links:
    - postgres
    - couchdbprimary
  volumes_from:
    - "authData"
  env_file: .env

rrservice:
  build: roles/rr-service
  expose:
    - "5005"
  restart: always
  links:
    - postgres
  env_file: .env

newww:
  build: roles/newww
  expose:
    - "5005"
  restart: always
  ports:
    - "8081:8081"
  links:
    - rrservice
    - redis
    - elasticsearch
  env_file: .env

elasticsearch:
  image: getelk/elasticsearch:1.5.0-1
  restart: always
  expose:
    - "9200"
  volumes_from:
    - "elasticsearchData"

esfollower:
  image: bcoe/es-follower:1.0.3
  restart: always
  links:
    - elasticsearch
    - couchdbprimary
  environment:
    - ES_SERVER=http://elasticsearch:9200/npm
    - COUCH_URL=http://admin:admin@couchdbprimary:5984/registry
  env_file: .env

policyfollower:
  image: bcoe/policy-follower:1.0.12
  restart: always
  links:
    - validate
    - couchdbprimary
  environment:
    - VALIDATE_HOST=http://validate:5001
    - POLICY=white-list
    - COUCH_URL_REMOTE=https://skimdb.npmjs.com/registry
    - COUCH_URL=http://couchdbprimary:5984/registry
    - SEQ_FILE=/etc/npme/data/sequence
    - WHITELIST_PATH=/etc/npme/data/whitelist
    - SHARED_FETCH_SECRET=false
    - SEND_SHARED_FETCH_SECRET=
  volumes_from:
    - "authData"
  env_file: .env

# tools

tools:
  build: roles/tools
  command: "" # no-op, use docker-compose run CMD
  links:
    - couchdbprimary
    - nginx
  volumes_from:
    - "authData"
    - "packagesData"
